import type { CompanyRole } from '@/Lib/tenant/types'

/** Fallback when role_permissions table is unavailable. */
const FALLBACK: Record<CompanyRole, string[]> = {
  owner: [
    'users.view',
    'users.manage',
    'users.invite',
    'quotes.view',
    'quotes.manage',
    'quotes.convert',
    'orders.view',
    'orders.manage',
    'orders.financial.view',
    'orders.materials.view',
    'orders.materials.prepare',
    'orders.materials.check',
    'orders.materials.dispatch',
    'orders.materials.return',
    'materials.rules.view',
    'materials.rules.manage',
    'customers.view',
    'customers.manage',
    'catalog.view',
    'catalog.manage',
    'agenda.view',
    'agenda.manage',
    'teams.view',
    'teams.manage',
    'company.settings',
    'audit.view',
  ],
  admin: [
    'users.view',
    'users.manage',
    'users.invite',
    'quotes.view',
    'quotes.manage',
    'quotes.convert',
    'orders.view',
    'orders.manage',
    'orders.financial.view',
    'orders.materials.view',
    'orders.materials.prepare',
    'orders.materials.check',
    'orders.materials.dispatch',
    'orders.materials.return',
    'materials.rules.view',
    'materials.rules.manage',
    'customers.view',
    'customers.manage',
    'catalog.view',
    'catalog.manage',
    'agenda.view',
    'agenda.manage',
    'teams.view',
    'teams.manage',
    'company.settings',
    'audit.view',
  ],
  manager: [
    'users.view',
    'quotes.view',
    'quotes.manage',
    'quotes.convert',
    'orders.view',
    'orders.manage',
    'orders.materials.view',
    'orders.materials.prepare',
    'orders.materials.check',
    'orders.materials.dispatch',
    'orders.materials.return',
    'materials.rules.view',
    'materials.rules.manage',
    'customers.view',
    'customers.manage',
    'catalog.view',
    'catalog.manage',
    'agenda.view',
    'agenda.manage',
    'teams.view',
    'teams.manage',
    'audit.view',
  ],
  sales: [
    'quotes.view',
    'quotes.manage',
    'quotes.convert',
    'orders.view',
    'orders.financial.view',
    'orders.materials.view',
    'materials.rules.view',
    'customers.view',
    'customers.manage',
    'catalog.view',
    'agenda.view',
    'teams.view',
  ],
  operator: [
    'quotes.view',
    'orders.view',
    'orders.manage',
    'orders.materials.view',
    'orders.materials.prepare',
    'orders.materials.check',
    'orders.materials.dispatch',
    'orders.materials.return',
    'materials.rules.view',
    'customers.view',
    'catalog.view',
    'agenda.view',
    'agenda.manage',
    'teams.view',
  ],
  kitchen: [
    'quotes.view',
    'orders.view',
    'orders.materials.view',
    'materials.rules.view',
    'catalog.view',
  ],
  finance: [
    'quotes.view',
    'orders.view',
    'orders.financial.view',
    'orders.materials.view',
    'materials.rules.view',
    'customers.view',
    'catalog.view',
    'audit.view',
  ],
  viewer: [
    'quotes.view',
    'orders.view',
    'orders.materials.view',
    'materials.rules.view',
    'customers.view',
    'catalog.view',
    'agenda.view',
    'teams.view',
  ],
}

export function fallbackPermissionsForRole(role: CompanyRole | null | undefined): string[] {
  if (!role) return []
  return FALLBACK[role] ?? []
}

export function hasPermission(
  permissions: string[] | null | undefined,
  key: string,
): boolean {
  return Boolean(permissions?.includes(key))
}

export function canManageUsers(permissions: string[]): boolean {
  return hasPermission(permissions, 'users.manage')
}

export function canInviteUsers(permissions: string[]): boolean {
  return hasPermission(permissions, 'users.invite') || canManageUsers(permissions)
}
